### PR TITLE
Add country flag emoji before country code in each proxy name field, some typo fix

### PR DESCRIPTION
**Pull request by sparkyvxcx**
hey, @zu1k cool project, I create this PR to add country flag emoji before each country code to make it more recognizable. Hope this will add some useability compared to the plain text one. Thank you! 😊 

Here are some screenshots of the effect:

Clash configuration:
clash

Surge configuration:
surge

### CODE REVIEW

**Comment by zu1k** [comment]
Is this done?

**Comment by sparkyvxcx** [comment]
> Is this done?

It looks good to me, I have tested it both from my local machine and mobile device (by using the clash configuration generated by proxypoll). It simply takes a given country code returned by MaxMindDB reader and finds its corresponding country flag, and finally append the flag emoji in front of country code. Thank you!

**Comment by sparkyvxcx** [comment]
Oops, sorry. I forgot to add the modified `pkg/proxy/geoip.go` source file while committing the original commit. It's my first PR and it's midnight, a little bit of nervous hope you could understand.

**Comment by zu1k** [comment]
Thanks for your work, this will make the name more user-friendly

**Comment by sparkyvxcx** [comment]
Thank you, @zu1k 😊 glad I can help out!

**Comment by wishcaiji** [comment]
i think you need add one function :  can choose the servers  under ping 200  or   some !

**Pull request merged**
